from django.db import models

class sqlserverconn(models.Model):
    Week=models.IntegerField()
    No=models.IntegerField()
    out=models.CharField(max_length=100)
    dateout=models.DateTimeField(max_length=100)
    dateoutno=models.IntegerField()
    inv=models.IntegerField()
    si=models.IntegerField()
    customer=models.CharField(max_length=100)
    pickdate=models.DateTimeField(max_length=100)
    closing=models.DateTimeField(max_length=100)
    etd=models.DateTimeField(max_length=100)
    sku1=models.IntegerField()
    sku2=models.IntegerField()
    sku3=models.IntegerField()
    sku4=models.IntegerField()
    sku5=models.IntegerField()
    sku6=models.IntegerField()
    sku7=models.IntegerField()
    sku8=models.IntegerField()
    sku9=models.IntegerField()
    sku10=models.IntegerField()
    sku11=models.IntegerField()
    sku12=models.IntegerField()
    sku13=models.IntegerField()
    sku14=models.IntegerField()
    sku15=models.IntegerField()
    sku16=models.IntegerField()
    sku17=models.IntegerField()
    sku18=models.IntegerField()
    sku19=models.IntegerField()
    sku20=models.IntegerField()
    sku21=models.IntegerField()
    sku22=models.IntegerField()
    sku23=models.IntegerField()
    sku24=models.IntegerField()
    sku25=models.IntegerField()
    squ26=models.IntegerField()
    sku27=models.IntegerField()
    sku28=models.IntegerField()
    sku29=models.IntegerField()
    sku30=models.IntegerField()
    remark=models.CharField(max_length=100)
    chksku1=models.CharField(max_length=100)
    chksku2=models.CharField(max_length=100)
    chksku3=models.CharField(max_length=100)
    chksku4=models.CharField(max_length=100)
    chksku5=models.CharField(max_length=100)
    chksku6=models.CharField(max_length=100)
    chksku7=models.CharField(max_length=100)
    chksku8=models.CharField(max_length=100)
    chksku9=models.CharField(max_length=100)
    chksku10=models.CharField(max_length=100)
    chksku11=models.CharField(max_length=100)
    chksku12=models.CharField(max_length=100)
    chksku13=models.CharField(max_length=100)
    chksku14=models.CharField(max_length=100)
    chksku15=models.CharField(max_length=100)
    chksku16=models.CharField(max_length=100)
    chksku17=models.CharField(max_length=100)
    chksku18=models.CharField(max_length=100)
    chksku19=models.CharField(max_length=100)
    chksku20=models.CharField(max_length=100)
    chksku21=models.CharField(max_length=100)
    chksku22=models.CharField(max_length=100)
    chksku23=models.CharField(max_length=100)
    chksku24=models.CharField(max_length=100)
    chksku25=models.CharField(max_length=100)
    chksku26=models.CharField(max_length=100)
    chksku27=models.CharField(max_length=100)
    chksku28=models.CharField(max_length=100)
    chksku29=models.CharField(max_length=100)
    chksku30=models.CharField(max_length=100)
    mktchk=models.IntegerField()
 




